"""Initial schema

Revision ID: 2a3ad493a301
Revises: 
Create Date: 2026-06-30 19:46:48.866465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a3ad493a301'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crashedcontainers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.String(length=100), nullable=True),
    sa.Column('container_name', sa.String(length=100), nullable=True),
    sa.Column('logs', sa.String(length=5000), nullable=True),
    sa.Column('crashedon', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crashedcontainers')
    # ### end Alembic commands ###
